[[keyboard.bindings]]
chars = "\u0006v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006h"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006t"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00060"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00061"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00062"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00063"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00064"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00065"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00066"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00067"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "{"
key = 28
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = 25
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 26
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "|"
key = 26
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 23
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 22
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[D"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006\u001B[C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006\u001B[A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006\u001B[B"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[D"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[C"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[A"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006\u001B[B"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006p"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0006n"
key = "Right"
mods = "Control"
