#!/bin/zsh

# Select a shell from the list of available shells (ignoring comment lines and empty lines) using fzf
selected_shell=$(grep -v '^\s*#' /etc/shells | grep -v '^\s*$' | fzf)

# If no shell is selected, exit the script
if [[ -z "$selected_shell" ]]; then
  echo "No shell selected. Exiting..."
  exit 1
fi

# Open the selected shell in a new tmux window
tmux neww "$selected_shell"

